config/routes.rb
Rails.application.routes.draw do
  resources :shifts
  resources :workers
  root "shifts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :worker, required: false

  validates_presence_of :start_date
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :shifts

  enum status: [ :medic, :interne, :interim ]

  validates_presence_of :first_name, :status
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy]

  # GET /shifts
  # GET /shifts.json
  def index
    @shifts = Shift.all.order(:id)
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
    @workers = Worker.all
  end

  # GET /shifts/1/edit
  def edit
    @workers = Worker.all
  end

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(shift_params)

    if @shift.save
      redirect_to @shift, notice: 'Shift was successfully created.'
    else
      @workers = Worker.all
      render :new
    end
  end

  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update
    if @shift.update(shift_params)
      redirect_to @shift, notice: 'Shift was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift.destroy
    redirect_to shifts_url, notice: 'Shift was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shift_params
      params.require(:shift).permit(:start_date, :worker_id)
    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all.order(:id)
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    if @worker.save
      redirect_to @worker, notice: 'Worker was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    if @worker.update(worker_params)
      redirect_to @worker, notice: 'Worker was successfully updated.'
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:first_name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planningdegarde</title>
    <%= csrf_meta_tags %>

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>



  <body>

  <!-- Static navbar -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Planning de garde</a>
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(shifts_path) %>"> <%= link_to "Shifts", shifts_path %></li>
        <li class="<%= 'active' if current_page?(workers_path) %>"> <%= link_to "Workers", workers_path %></li>
      </ul>
    </div><!--/.container-fluid -->
  </nav>

  <div class="container body-content" >
    <%= yield %>
  </div>
  </body>
</html>

app/views/shifts/_form.html.erb
<%= form_with(model: shift, local: true, html: { class: 'form-horizontal center' }) do |form| %>
  <% if shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <% if shift.new_record? %>
        <%= form.date_select :start_date, id: :shift_start_date %>
    <% else %>
        <%= form.label shift.start_date %>
  <% end %>
  </div>

  <div class="field">
    <%= form.label :worker_id %>
    <%= form.select :worker_id, @workers.map{ |worker| [worker.first_name, worker.id] }, :include_blank => true %>
  </div>

  <div class="actions">
    <%= form.submit(shift.new_record? ? nil : "Assign") %>
  </div>
<% end %>

app/views/shifts/_list_for_worker.html.erb
<h3>List of Shifts</h3>
<table class="table">
  <thead>
  <tr>
    <th>Id</th>
    <th>Start date</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% shifts.each do |shift| %>
      <tr>
        <td><%= shift.id %></td>
        <td><%= shift.start_date %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift), class: "btn btn-info" %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/shifts/edit.html.erb
<h1>Editing Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Show', @shift, class: "btn btn-default" %> |
<%= link_to 'Back', shifts_path, class: "btn btn-default"  %>

app/views/shifts/index.html.erb
<p id="notice"><%= notice %></p>

<div>
  <%= link_to "Create Shift", new_shift_path, class: "btn btn-info"  %>
</div>
<br>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Start date</th>
      <th>Worker</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.id %></td>
        <td><%= shift.start_date %></td>
        <td><%= link_to shift.worker.try(:first_name) || "Unassigned", shift.worker %></td>
        <td><%= link_to shift.worker ? "Change assigned" : "Assign", edit_shift_path(shift), class: "btn btn-info"  %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/shifts/new.html.erb
<h2>New Shift</h2>

<%= render 'form', shift: @shift %>

<%= link_to 'Back', shifts_path, class: "btn btn-default"  %>

app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @shift.start_date %>
</p>

<p>
  <strong>Worker:</strong>
  <%= link_to @shift.worker.try(:first_name) || "Unassigned", @shift.worker %>
</p>

<%= link_to 'Edit', edit_shift_path(@shift), class: "btn btn-info"  %>
<%= link_to 'Back', shifts_path, class: "btn btn-default"  %>

app/views/workers/_form.html.erb
<%= form_with(model: worker, local: true, html: { class: 'form-horizontal center' }) do |form| %>
  <% if worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :worker_first_name %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Worker.statuses.keys %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<h1>Editing Worker</h1>

<%= render 'form', worker: @worker %>

<%= link_to 'Show', @worker, class: "btn btn-default"  %> |
<%= link_to 'Back', workers_path, class: "btn btn-default"  %>

app/views/workers/index.html.erb
<p id="notice"><%= notice %></p>

<div>
  <%= link_to "New Worker", new_worker_path, class: "btn btn-info"  %>
</div>
<br>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>First name</th>
      <th>Status</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.id %></td>
        <td><%= worker.first_name %></td>
        <td><%= worker.status %></td>
        <td><%= link_to 'Show', worker, class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_worker_path(worker), class: "btn btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/workers/new.html.erb
<h2>New Worker</h2>

<%= render 'form', worker: @worker %>

<%= link_to 'Back', workers_path, class: "btn btn-default"  %>

app/views/workers/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Worker: <%= @worker.first_name %></h3>

<p>
  <strong>Status:</strong>
  <%= @worker.status %>
</p>

<%= link_to 'Edit', edit_worker_path(@worker), class: "btn btn-info"  %>
<%= link_to 'Back', workers_path, class: "btn btn-default"  %>

<%= render partial: "shifts/list_for_worker", locals: {shifts: @worker.shifts} %>